package BlockIo


func (blockIo *Client) GetNewAddress(args string) map[string]interface{}{ return blockIo._request("POST", "get_new_address", args); }
func (blockIo *Client) GetBalance(args string) map[string]interface{}{ return blockIo._request("GET", "get_balance", args); }
func (blockIo *Client) GetMyAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "get_my_addresses", args); }
func (blockIo *Client) GetAddressReceived(args string) map[string]interface{}{ return blockIo._request("POST", "get_address_received", args); }
func (blockIo *Client) GetAddressByLabel(args string) map[string]interface{}{ return blockIo._request("POST", "get_address_by_label", args); }
func (blockIo *Client) GetAddressBalance(args string) map[string]interface{}{ return blockIo._request("POST", "get_address_balance", args); }
func (blockIo *Client) CreateUser(args string) map[string]interface{}{ return blockIo._request("POST", "create_user", args); }
func (blockIo *Client) GetUsers(args string) map[string]interface{}{ return blockIo._request("POST", "get_users", args); }
func (blockIo *Client) GetUserBalance(args string) map[string]interface{}{ return blockIo._request("POST", "get_user_balance", args); }
func (blockIo *Client) GetUserAddress(args string) map[string]interface{}{ return blockIo._request("POST", "get_user_address", args); }
func (blockIo *Client) GetUserReceived(args string) map[string]interface{}{ return blockIo._request("POST", "get_user_received", args); }
func (blockIo *Client) GetTransactions(args string) map[string]interface{}{ return blockIo._request("POST", "get_transactions", args); }
func (blockIo *Client) SignAndFinalizeWithdrawal(args string) map[string]interface{}{ return blockIo._request("POST", "sign_and_finalize_withdrawal", args); }
func (blockIo *Client) GetNewDtrustAddress(args string) map[string]interface{}{ return blockIo._request("POST", "get_new_dtrust_address", args); }
func (blockIo *Client) GetMyDtrustAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "get_my_dtrust_addresses", args); }
func (blockIo *Client) GetDtrustAddressByLabel(args string) map[string]interface{}{ return blockIo._request("POST", "get_dtrust_address_by_label", args); }
func (blockIo *Client) GetDtrustTransactions(args string) map[string]interface{}{ return blockIo._request("POST", "get_dtrust_transactions", args); }
func (blockIo *Client) GetDtrustAddressBalance(args string) map[string]interface{}{ return blockIo._request("POST", "get_dtrust_address_balance", args); }
func (blockIo *Client) GetNetworkFeeEstimate(args string) map[string]interface{}{ return blockIo._request("POST", "get_network_fee_estimate", args); }
func (blockIo *Client) ArchiveAddress(args string) map[string]interface{}{ return blockIo._request("POST", "archive_address", args); }
func (blockIo *Client) UnarchiveAddress(args string) map[string]interface{}{ return blockIo._request("POST", "unarchive_address", args); }
func (blockIo *Client) GetMyArchivedAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "get_my_archived_addresses", args); }
func (blockIo *Client) ArchiveDtrustAddress(args string) map[string]interface{}{ return blockIo._request("POST", "archive_dtrust_address", args); }
func (blockIo *Client) UnarchiveDtrustAddress(args string) map[string]interface{}{ return blockIo._request("POST", "unarchive_dtrust_address", args); }
func (blockIo *Client) GetMyArchivedDtrustAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "get_my_archived_dtrust_addresses", args); }
func (blockIo *Client) GetDtrustNetworkFeeEstimate(args string) map[string]interface{}{ return blockIo._request("POST", "get_dtrust_network_fee_estimate", args); }
func (blockIo *Client) CreateNotification(args string) map[string]interface{}{ return blockIo._request("POST", "create_notification", args); }
func (blockIo *Client) DisableNotification(args string) map[string]interface{}{ return blockIo._request("POST", "disable_notification", args); }
func (blockIo *Client) EnableNotification(args string) map[string]interface{}{ return blockIo._request("POST", "enable_notification", args); }
func (blockIo *Client) GetNotifications(args string) map[string]interface{}{ return blockIo._request("POST", "get_notifications", args); }
func (blockIo *Client) GetRecentNotificationEvents(args string) map[string]interface{}{ return blockIo._request("POST", "get_recent_notification_events", args); }
func (blockIo *Client) DeleteNotification(args string) map[string]interface{}{ return blockIo._request("POST", "delete_notification", args); }
func (blockIo *Client) ValidateApiKey(args string) map[string]interface{}{ return blockIo._request("POST", "validate_api_key", args); }
func (blockIo *Client) SignTransation(args string) map[string]interface{}{ return blockIo._request("POST", "sign_transaction", args); }
func (blockIo *Client) FinalizeTransaction(args string) map[string]interface{}{ return blockIo._request("POST", "finalize_transaction", args); }
func (blockIo *Client) GetMyAddressesWithoutBalances(args string) map[string]interface{}{ return blockIo._request("POST", "get_my_addresses_without_balances", args); }
func (blockIo *Client) GetRawTransaction(args string) map[string]interface{}{ return blockIo._request("POST", "get_raw_transaction", args); }
func (blockIo *Client) GetDtrustBalance(args string) map[string]interface{}{ return blockIo._request("POST", "get_dtrust_balance", args); }
func (blockIo *Client) ArchiveAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "archive_addresses", args); }
func (blockIo *Client) UnarchiveAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "unarchive_addresses", args); }
func (blockIo *Client) ArchiveDtrustAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "archive_dtrust_addresses", args); }
func (blockIo *Client) UnarchiveDtrustAddresses(args string) map[string]interface{}{ return blockIo._request("POST", "unarchive_dtrust_addresses", args); }
func (blockIo *Client) IsValidAddress(args string) map[string]interface{}{ return blockIo._request("POST", "is_valid_address", args); }
func (blockIo *Client) GetCurrentPrice(args string) map[string]interface{}{ return blockIo._request("POST", "get_current_price", args); }
func (blockIo *Client) GetAccountInfo(args string) map[string]interface{}{ return blockIo._request("POST", "get_account_info", args); }